//userFormReducer
export const LOAD_USERS = "LOAD_USERS";
export const TOGGLE_ADD = "TOGGLE_ADD";
export const OPEN_EDIT = "OPEN_EDIT";
export const CLOSE_EDIT = "CLOSE_EDIT";
export const CHANGE_FIRST_NAME = "CHANGE_FIRST_NAME";
export const CHANGE_LAST_NAME = "CHANGE_LAST_NAME";
export const CHANGE_EMAIL = "CHANGE_EMAIL";
export const CHANGE_ROLE = "CHANGE_ROLE";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const RESET_FORM = "RESET_FORM";

// productFormReducer
export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const TOGGLE_ADD_PRODUCT = "TOGGLE_ADD_PRODUCT";
export const SET_IMAGE = "SET_IMAGE";
export const OPEN_EDIT_PRODUCT = "OPEN_EDIT_PRODUCT";
export const CLOSE_EDIT_PRODUCT = "CLOSE_EDIT_PRODUCT";
export const CHANGE_PRODUCT_NAME = "CHANGE_PRODUCT_NAME";
export const CHANGE_PRODUCT_PRICE = "CHANGE_PRODUCT_PRICE";
export const CHANGE_PRODUCT_CATEGORY = "CHANGE_PRODUCT_CATEGORY";
export const CHANGE_PRODUCT_QUANTITY = "CHANGE_PRODUCT_QUANTITY";
export const CHANGE_PRODUCT_DESCRIPTION = "CHANGE_PRODUCT_DESCRIPTION";
export const RESET_PRODUCT_FORM = "RESET_PRODUCT_FORM";

//checkoutReducer
export const SET_ORDER = "SET_ORDER";
export const PROCESS_ORDER_PAYMENT = "PROCESS_ORDER_PAYMENT";
export const SUCCESSFUL_PAYMENT = "SUCCESSFUL_PAYMENT";
export const SET_ITEMS_PRICE = "SET_ITEMS_PRICE";
export const SET_SHIPPING_PRICE = "SET_SHIPPING_PRICE";
export const SET_LOADING = "SET_LOADING";
export const SET_CHECKOUT_STEP = "SET_CHECKOUT_STEP";
export const SET_IS_PROCESSING_PAYMENT = "SET_IS_PROCESSING_PAYMENT";
export const RESET_CHECKOUT = "RESET_CHECKOUT";

//authReducer
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
